name: Build
on:
  workflow_dispatch:
    inputs:
      flex_repo:
        description: 'Custom FLEX GitHub Repository URL'
        required: false
        default: 'https://github.com/FLEXTool/FLEX'
      flex_branch:
        description: 'Custom FLEX GitHub Repository Branch'
        required: false
        default: 'master'
  push:
    branches:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-14
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Theos
      uses: Randomblock1/theos-action@v1.4
      with:
        theos-dir: ${{ github.workspace }}/theos
        theos-src: https://github.com/theos/theos
        theos-sdks: https://github.com/theos/sdks
        theos-sdks-branch: master
        orion: false
    - name: Run build script
      run: chmod +x ./build.sh && ./build.sh '${{ github.event.inputs.flex_repo }}' '${{ github.event.inputs.flex_branch }}'
